list(APPEND SOURCE_FILES
        binding/sk_alpha_type.cpp
        binding/sk_android_codec.cpp
        binding/sk_annotation.cpp
        binding/sk_auto_canvas_restore.cpp
        binding/sk_avif_decoder.cpp
        binding/sk_b_box_hierarchy.cpp
        binding/sk_bitmap.cpp
        binding/sk_blend_mode.cpp
        binding/sk_blender.cpp
        binding/sk_blenders.cpp
        binding/sk_bmp_decoder.cpp
        binding/sk_canvas.cpp
        binding/sk_capabilities.cpp
        binding/sk_codec.cpp
        binding/sk_codecs.cpp
        binding/sk_color_4f.cpp
        binding/sk_color_filter.cpp
        binding/sk_color_filters.cpp
        binding/sk_color_info.cpp
        binding/sk_color_matrix_filter.cpp
        binding/sk_color_matrix.cpp
        binding/sk_color_priv.cpp
        binding/sk_color_space_primaries.cpp
        binding/sk_color_space.cpp
        binding/sk_color_table.cpp
        binding/sk_color.cpp
        binding/sk_contour_measure_iter.cpp
        binding/sk_contour_measure.cpp
        binding/sk_corner_path_effect.cpp
        binding/sk_cubic_map.cpp
        binding/sk_cubic_resampler.cpp
        binding/sk_dash_path_effect.cpp
        binding/sk_data_table.cpp
        binding/sk_data.cpp
        binding/sk_discrete_path_effect.cpp
        binding/sk_document.cpp
        binding/sk_drawable.cpp
        binding/sk_dynamic_memory_w_stream.cpp
        binding/sk_encoded_origin.cpp
        binding/sk_encoder.cpp
        binding/sk_executor.cpp
        binding/sk_file_stream.cpp
        binding/sk_file_w_stream.cpp
        binding/sk_flattenable.cpp
        binding/sk_font_arguments.cpp
        binding/sk_font_metrics.cpp
#        binding/sk_font_mgr_fontconfig.cpp
        binding/sk_font_mgr.cpp
        binding/sk_font_style_set.cpp
        binding/sk_font_style.cpp
        binding/sk_font.cpp
#        binding/sk_gif_decoder.cpp
        binding/sk_gradient_shader.cpp
        binding/sk_graphics.cpp
        binding/sk_high_contrast_config.cpp
        binding/sk_high_contrast_filter.cpp
        binding/sk_i_point.cpp
        binding/sk_i_rect.cpp
        binding/sk_i_size.cpp
        binding/sk_icc.cpp
        binding/sk_ico_decoder.cpp
        binding/sk_image_filter.cpp
        binding/sk_image_filters.cpp
        binding/sk_image_generator.cpp
        binding/sk_image_info.cpp
        binding/sk_image.cpp
        binding/sk_images.cpp
        binding/sk_jpeg_decoder.cpp
#        binding/sk_jpeg_encoder.cpp
        binding/sk_jpegxl_decoder.cpp
        binding/sk_line_2d_path_effect.cpp
        binding/sk_luma_color_filter.cpp
        binding/sk_m_44.cpp
        binding/sk_malloc_pixel_ref.cpp
        binding/sk_mask.cpp
        binding/sk_mask_builder.cpp
        binding/sk_mask_filter.cpp
        binding/sk_matrix.cpp
        binding/sk_memory_stream.cpp
        binding/sk_mesh.cpp
        binding/sk_mesh_specification.cpp
        binding/sk_meshes.cpp
        binding/sk_op_builder.cpp
#        binding/sk_open_type_svg_decoder.cpp
        binding/sk_overdraw_canvas.cpp
        binding/sk_overdraw_color_filter.cpp
        binding/sk_paint.cpp
        binding/sk_path_1d_path_effect.cpp
        binding/sk_path_2d_path_effect.cpp
        binding/sk_path_builder.cpp
        binding/sk_path_effect.cpp
        binding/sk_path_measure.cpp
        binding/sk_path.cpp
#        binding/sk_pdf.cpp
        binding/sk_perlin_noise_shader.cpp
        binding/sk_picture_recorder.cpp
        binding/sk_picture.cpp
        binding/sk_pixel_ref.cpp
        binding/sk_pixmap_utils.cpp
        binding/sk_pixmap.cpp
        binding/sk_png_decoder.cpp
        binding/sk_png_encoder.cpp
        binding/sk_point_3.cpp
        binding/sk_point.cpp
        binding/sk_r_rect.cpp
#        binding/sk_raster_handle_allocator.cpp
#        binding/sk_raw_decoder.cpp
        binding/sk_read_buffer.cpp
        binding/sk_rect.cpp
        binding/sk_ref_cnt_base.cpp
        binding/sk_ref_cnt.cpp
        binding/sk_region.cpp
        binding/sk_rsx_form.cpp
        binding/sk_runtime_blend_builder.cpp
        binding/sk_runtime_color_filter_builder.cpp
        binding/sk_runtime_effect_builder.cpp
        binding/sk_runtime_effect.cpp
        binding/sk_runtime_shader_builder.cpp
        binding/sk_sampling_options.cpp
        binding/sk_shader_mask_filter.cpp
        binding/sk_shader.cpp
        binding/sk_shaders.cpp
        binding/sk_size.cpp
        binding/sk_stream_asset.cpp
        binding/sk_stream_memory.cpp
        binding/sk_stream_rewindable.cpp
        binding/sk_stream_seekable.cpp
        binding/sk_stream.cpp
        binding/sk_string.cpp
        binding/sk_stroke_rec.cpp
        binding/sk_surface_props.cpp
        binding/sk_surface.cpp
        binding/sk_surfaces.cpp
        binding/sk_table_mask_filter.cpp
#        binding/sk_text_blob_builder_run_handler.cpp
        binding/sk_text_blob_builder.cpp
        binding/sk_text_blob.cpp
        binding/sk_tiled_image_utils.cpp
        binding/sk_trace_memory_dump.cpp
        binding/sk_trim_path_effect.cpp
        binding/sk_typeface.cpp
        binding/sk_un_pre_multiply.cpp
        binding/sk_v2.cpp
        binding/sk_v3.cpp
        binding/sk_v4.cpp
        binding/sk_vertices.cpp
        binding/sk_w_stream.cpp
        binding/sk_wbmp_decoder.cpp
        binding/sk_webp_decoder.cpp
#        binding/sk_webp_encoder.cpp
        binding/sk_write_buffer.cpp
        binding/sk_yuva_info.cpp
        binding/sk_yuva_pixmap_info.cpp
        binding/sk_yuva_pixmaps.cpp
)
