list(APPEND SOURCE_FILES
        src/base/SkArenaAlloc.cpp
        src/base/SkBase64.cpp
        src/base/SkBezierCurves.cpp
        src/base/SkBlockAllocator.cpp
        src/base/SkBuffer.cpp
        src/base/SkContainers.cpp
        src/base/SkCubics.cpp
        src/base/SkDebug.cpp
        src/base/SkDeque.cpp
        src/base/SkFloatingPoint.cpp
        src/base/SkHalf.cpp
        src/base/SkMalloc.cpp
        src/base/SkMathPriv.cpp
        src/base/SkQuads.cpp
        src/base/SkSafeMath.cpp
        src/base/SkSemaphore.cpp
        src/base/SkSharedMutex.cpp
        src/base/SkSpinlock.cpp
        src/base/SkTDArray.cpp
        src/base/SkThreadID.cpp
        src/base/SkTime.cpp
        src/base/SkTSearch.cpp
        src/base/SkUTF.cpp
        src/base/SkUtils.cpp
        src/codec/SkAndroidCodec.cpp
        src/codec/SkAndroidCodecAdapter.cpp
        # src/codec/SkAvifCodec.cpp
        src/codec/SkBmpBaseCodec.cpp
        src/codec/SkBmpCodec.cpp
        src/codec/SkBmpMaskCodec.cpp
        src/codec/SkBmpRLECodec.cpp
        src/codec/SkBmpStandardCodec.cpp
        src/codec/SkCodec.cpp
        src/codec/SkCodecImageGenerator.cpp
        src/codec/SkColorPalette.cpp
        src/codec/SkEncodedInfo.cpp
        src/codec/SkExif.cpp
        src/codec/SkHeifCodec.cpp
        src/codec/SkIcoCodec.cpp
        src/codec/SkImageGenerator_FromEncoded.cpp
        src/codec/SkJpegCodec.cpp
        src/codec/SkJpegDecoderMgr.cpp
        src/codec/SkJpegMultiPicture.cpp
        src/codec/SkJpegSegmentScan.cpp
        src/codec/SkJpegSourceMgr.cpp
        src/codec/SkJpegUtility.cpp
        #  src/codec/SkJpegxlCodec.cpp
        #  src/codec/SkJpegXmp.cpp
        src/codec/SkMasks.cpp
        src/codec/SkMaskSwizzler.cpp
        src/codec/SkParseEncodedOrigin.cpp
        src/codec/SkPixmapUtils.cpp
        src/codec/SkPngCodec.cpp
        src/codec/SkSampledCodec.cpp
        src/codec/SkSampler.cpp
        src/codec/SkSwizzler.cpp
        src/codec/SkTiffUtility.cpp
        src/codec/SkWbmpCodec.cpp
        src/codec/SkWebpCodec.cpp
        # src/codec/SkXmp.cpp
        src/core/SkAAClip.cpp
        src/core/SkAlphaRuns.cpp
        src/core/SkAnalyticEdge.cpp
        src/core/SkAnnotation.cpp
        src/core/SkATrace.cpp
        src/core/SkAutoPixmapStorage.cpp
        src/core/SkBBHFactory.cpp
        src/core/SkBigPicture.cpp
        src/core/SkBitmap.cpp
        src/core/SkBitmapCache.cpp
        src/core/SkBitmapDevice.cpp
        src/core/SkBitmapProcState_matrixProcs.cpp
        src/core/SkBitmapProcState_opts_hsw.cpp
        src/core/SkBitmapProcState_opts_ssse3.cpp
        src/core/SkBitmapProcState_opts.cpp
        src/core/SkBitmapProcState.cpp
        src/core/SkBlendMode.cpp
        src/core/SkBlendModeBlender.cpp
        src/core/SkBlitMask_opts_ssse3.cpp
        src/core/SkBlitMask_opts.cpp
        src/core/SkBlitRow_D32.cpp
        src/core/SkBlitRow_opts_hsw.cpp
        src/core/SkBlitRow_opts.cpp
        src/core/SkBlitter_A8.cpp
        src/core/SkBlitter_ARGB32.cpp
        src/core/SkBlitter_Sprite.cpp
        src/core/SkBlitter.cpp
        src/core/SkBlurMask.cpp
        src/core/SkBlurMaskFilterImpl.cpp
        src/core/SkCachedData.cpp
        src/core/SkCanvas_Raster.cpp
        src/core/SkCanvas.cpp
        src/core/SkCanvasPriv.cpp
        src/core/SkCapabilities.cpp
        src/core/SkChecksum.cpp
        src/core/SkClipStack.cpp
        src/core/SkClipStackDevice.cpp
        src/core/SkColor.cpp
        src/core/SkColorFilter.cpp
        src/core/SkColorSpace.cpp
        src/core/SkColorSpaceXformSteps.cpp
        src/core/SkColorTable.cpp
        src/core/SkCompressedDataUtils.cpp
        src/core/SkContourMeasure.cpp
        src/core/SkConvertPixels.cpp
        src/core/SkCpu.cpp
        src/core/SkCubicClipper.cpp
        src/core/SkCubicMap.cpp
        src/core/SkData.cpp
        src/core/SkDataTable.cpp
        src/core/SkDescriptor.cpp
        src/core/SkDevice.cpp
        src/core/SkDistanceFieldGen.cpp
        src/core/SkDocument.cpp
        src/core/SkDraw_atlas.cpp
        src/core/SkDraw_text.cpp
        src/core/SkDraw_vertices.cpp
        src/core/SkDraw.cpp
        src/core/SkDrawable.cpp
        src/core/SkDrawBase.cpp
        src/core/SkDrawLooper.cpp
        src/core/SkDrawShadowInfo.cpp
        src/core/SkEdge.cpp
        src/core/SkEdgeBuilder.cpp
        src/core/SkEdgeClipper.cpp
        src/core/SkExecutor.cpp
        src/core/SkFlattenable.cpp
        src/core/SkFont_serial.cpp
        src/core/SkFont.cpp
        src/core/SkFontDescriptor.cpp
        src/core/SkFontMetricsPriv.cpp
        src/core/SkFontMgr.cpp
        src/core/SkFontStream.cpp
        src/core/SkGaussFilter.cpp
        src/core/SkGeometry.cpp
        src/core/SkGlobalInitialization_core.cpp
        src/core/SkGlyph.cpp
        src/core/SkGlyphRunPainter.cpp
        src/core/SkGraphics.cpp
        src/core/SkIDChangeListener.cpp
        src/core/SkImageFilter.cpp
        src/core/SkImageFilterCache.cpp
        src/core/SkImageFilterTypes.cpp
        src/core/SkImageGenerator.cpp
        src/core/SkImageInfo.cpp
        src/core/SkLatticeIter.cpp
        src/core/SkLineClipper.cpp
        src/core/SkLocalMatrixImageFilter.cpp
        src/core/SkM44.cpp
        src/core/SkMallocPixelRef.cpp
        src/core/SkMask.cpp
        src/core/SkMaskBlurFilter.cpp
        src/core/SkMaskCache.cpp
        src/core/SkMaskFilter.cpp
        src/core/SkMaskGamma.cpp
        src/core/SkMatrix.cpp
        src/core/SkMatrixInvert.cpp
        src/core/SkMD5.cpp
        src/core/SkMemset_opts_avx.cpp
        src/core/SkMemset_opts_erms.cpp
        src/core/SkMemset_opts.cpp
        src/core/SkMesh.cpp
        src/core/SkMipmap.cpp
        src/core/SkMipmapAccessor.cpp
        src/core/SkMipmapBuilder.cpp
        src/core/SkMipmapDrawDownSampler.cpp
        src/core/SkMipmapHQDownSampler.cpp
        src/core/SkOpts.cpp
        src/core/SkOverdrawCanvas.cpp
        src/core/SkPaint.cpp
        src/core/SkPaintPriv.cpp
        src/core/SkPath_serial.cpp
        src/core/SkPath.cpp
        src/core/SkPathBuilder.cpp
        src/core/SkPathEffect.cpp
        src/core/SkPathMeasure.cpp
        src/core/SkPathRef.cpp
        src/core/SkPathUtils.cpp
        src/core/SkPicture.cpp
        src/core/SkPictureData.cpp
        src/core/SkPictureFlat.cpp
        src/core/SkPicturePlayback.cpp
        src/core/SkPictureRecord.cpp
        src/core/SkPictureRecorder.cpp
        src/core/SkPixelRef.cpp
        src/core/SkPixmap.cpp
        src/core/SkPixmapDraw.cpp
        src/core/SkPoint.cpp
        src/core/SkPoint3.cpp
        src/core/SkPtrRecorder.cpp
        src/core/SkQuadClipper.cpp
        src/core/SkRasterClip.cpp
        src/core/SkRasterPipeline.cpp
        src/core/SkRasterPipelineBlitter.cpp
        src/core/SkReadBuffer.cpp
        src/core/SkReadPixelsRec.cpp
        src/core/SkRecord.cpp
        src/core/SkRecordDraw.cpp
        src/core/SkRecordedDrawable.cpp
        src/core/SkRecorder.cpp
        src/core/SkRecordOpts.cpp
        src/core/SkRecords.cpp
        src/core/SkRect.cpp
        src/core/SkRegion_path.cpp
        src/core/SkRegion.cpp
        src/core/SkResourceCache.cpp
        src/core/SkRRect.cpp
        src/core/SkRSXform.cpp
        src/core/SkRTree.cpp
        src/core/SkRuntimeBlender.cpp
        src/core/SkRuntimeEffect.cpp
        src/core/SkScalar.cpp
        src/core/SkScalerContext.cpp
        src/core/SkScan_AAAPath.cpp
        src/core/SkScan_Antihair.cpp
        src/core/SkScan_AntiPath.cpp
        src/core/SkScan_Hairline.cpp
        src/core/SkScan_Path.cpp
        src/core/SkScan_SAAPath.cpp
        src/core/SkScan.cpp
        src/core/SkSLTypeShared.cpp
        src/core/SkSpecialImage.cpp
        src/core/SkSpriteBlitter_ARGB32.cpp
        src/core/SkStream.cpp
        src/core/SkStrike.cpp
        src/core/SkStrikeCache.cpp
        src/core/SkStrikeSpec.cpp
        src/core/SkString.cpp
        src/core/SkStringUtils.cpp
        src/core/SkStroke.cpp
        src/core/SkStrokeRec.cpp
        src/core/SkStrokerPriv.cpp
        src/core/SkSwizzle.cpp
        src/core/SkSwizzler_opts_hsw.cpp
        src/core/SkSwizzler_opts_ssse3.cpp
        src/core/SkSwizzler_opts.cpp
        src/core/SkTaskGroup.cpp
        src/core/SkTextBlob.cpp
        src/core/SkTextBlobTrace.cpp
        src/core/SkTypeface_remote.cpp
        src/core/SkTypeface.cpp
        src/core/SkTypefaceCache.cpp
        src/core/SkUnPreMultiply.cpp
        src/core/SkVertices.cpp
        src/core/SkVertState.cpp
        src/core/SkWriteBuffer.cpp
        src/core/SkWritePixelsRec.cpp
        src/core/SkWriter32.cpp
        src/core/SkYUVAInfo.cpp
        src/core/SkYUVAPixmaps.cpp
        src/core/SkYUVMath.cpp
        src/core/SkYUVPlanesCache.cpp
        src/effects/colorfilters/SkBlendModeColorFilter.cpp
        src/effects/colorfilters/SkColorFilterBase.cpp
        src/effects/colorfilters/SkColorSpaceXformColorFilter.cpp
        src/effects/colorfilters/SkComposeColorFilter.cpp
        src/effects/colorfilters/SkGaussianColorFilter.cpp
        src/effects/colorfilters/SkMatrixColorFilter.cpp
        src/effects/colorfilters/SkRuntimeColorFilter.cpp
        src/effects/colorfilters/SkTableColorFilter.cpp
        src/effects/colorfilters/SkWorkingFormatColorFilter.cpp
        src/effects/imagefilters/SkBlendImageFilter.cpp
        src/effects/imagefilters/SkBlurImageFilter.cpp
        src/effects/imagefilters/SkColorFilterImageFilter.cpp
        src/effects/imagefilters/SkComposeImageFilter.cpp
        src/effects/imagefilters/SkCropImageFilter.cpp
        src/effects/imagefilters/SkDisplacementMapImageFilter.cpp
        src/effects/imagefilters/SkDropShadowImageFilter.cpp
        src/effects/imagefilters/SkImageImageFilter.cpp
        src/effects/imagefilters/SkLightingImageFilter.cpp
        src/effects/imagefilters/SkMagnifierImageFilter.cpp
        src/effects/imagefilters/SkMatrixConvolutionImageFilter.cpp
        src/effects/imagefilters/SkMatrixTransformImageFilter.cpp
        src/effects/imagefilters/SkMergeImageFilter.cpp
        src/effects/imagefilters/SkMorphologyImageFilter.cpp
        src/effects/imagefilters/SkPictureImageFilter.cpp
        src/effects/imagefilters/SkRuntimeImageFilter.cpp
        src/effects/imagefilters/SkShaderImageFilter.cpp
        src/effects/Sk1DPathEffect.cpp
        src/effects/Sk2DPathEffect.cpp
        src/effects/SkBlenders.cpp
        src/effects/SkColorMatrix.cpp
        src/effects/SkColorMatrixFilter.cpp
        src/effects/SkCornerPathEffect.cpp
        src/effects/SkDashPathEffect.cpp
        src/effects/SkDiscretePathEffect.cpp
        src/effects/SkEmbossMask.cpp
        src/effects/SkEmbossMaskFilter.cpp
        src/effects/SkHighContrastFilter.cpp
        src/effects/SkLayerDrawLooper.cpp
        src/effects/SkShaderMaskFilterImpl.cpp
        src/effects/SkTableMaskFilter.cpp
        src/effects/SkTrimPathEffect.cpp
        # src/encode/SkPngEncoder_none.cpp
        src/encode/SkEncoder.cpp
        src/encode/SkICC.cpp
        src/encode/SkPngEncoderImpl.cpp
        src/image/SkImage_AndroidFactories.cpp
        src/image/SkImage_Base.cpp
        src/image/SkImage_Lazy.cpp
        src/image/SkImage_LazyFactories.cpp
        src/image/SkImage_Picture.cpp
        src/image/SkImage_Raster.cpp
        src/image/SkImage_RasterFactories.cpp
        src/image/SkImage.cpp
        src/image/SkPictureImageGenerator.cpp
        src/image/SkRescaleAndReadPixels.cpp
        src/image/SkSurface_Base.cpp
        src/image/SkSurface_Null.cpp
        src/image/SkSurface_Raster.cpp
        src/image/SkSurface.cpp
        src/image/SkTiledImageUtils.cpp
        src/opts/SkOpts_hsw.cpp
        src/pathops/SkAddIntersections.cpp
        src/pathops/SkDConicLineIntersection.cpp
        src/pathops/SkDCubicLineIntersection.cpp
        src/pathops/SkDCubicToQuads.cpp
        src/pathops/SkDLineIntersection.cpp
        src/pathops/SkDQuadLineIntersection.cpp
        src/pathops/SkIntersections.cpp
        src/pathops/SkOpAngle.cpp
        src/pathops/SkOpBuilder.cpp
        src/pathops/SkOpCoincidence.cpp
        src/pathops/SkOpContour.cpp
        src/pathops/SkOpCubicHull.cpp
        src/pathops/SkOpEdgeBuilder.cpp
        src/pathops/SkOpSegment.cpp
        src/pathops/SkOpSpan.cpp
        src/pathops/SkPathOpsAsWinding.cpp
        src/pathops/SkPathOpsCommon.cpp
        src/pathops/SkPathOpsConic.cpp
        src/pathops/SkPathOpsCubic.cpp
        src/pathops/SkPathOpsCurve.cpp
        src/pathops/SkPathOpsDebug.cpp
        src/pathops/SkPathOpsLine.cpp
        src/pathops/SkPathOpsOp.cpp
        src/pathops/SkPathOpsQuad.cpp
        src/pathops/SkPathOpsRect.cpp
        src/pathops/SkPathOpsSimplify.cpp
        src/pathops/SkPathOpsTightBounds.cpp
        src/pathops/SkPathOpsTSect.cpp
        src/pathops/SkPathOpsTypes.cpp
        src/pathops/SkPathOpsWinding.cpp
        src/pathops/SkPathWriter.cpp
        src/pathops/SkReduceOrder.cpp
        src/ports/SkDebug_stdio.cpp
        src/ports/SkGlobalInitialization_default.cpp
        src/ports/SkMemory_malloc.cpp
        src/ports/SkOSFile_stdio.cpp
        src/shaders/gradients/SkConicalGradient.cpp
        src/shaders/gradients/SkGradientBaseShader.cpp
        src/shaders/gradients/SkLinearGradient.cpp
        src/shaders/gradients/SkRadialGradient.cpp
        src/shaders/gradients/SkSweepGradient.cpp
        src/shaders/SkBitmapProcShader.cpp
        src/shaders/SkBlendShader.cpp
        src/shaders/SkColorFilterShader.cpp
        src/shaders/SkColorShader.cpp
        src/shaders/SkCoordClampShader.cpp
        src/shaders/SkEmptyShader.cpp
        src/shaders/SkGainmapShader.cpp
        src/shaders/SkImageShader.cpp
        src/shaders/SkLocalMatrixShader.cpp
        src/shaders/SkPerlinNoiseShaderImpl.cpp
        src/shaders/SkPictureShader.cpp
        src/shaders/SkRuntimeShader.cpp
        src/shaders/SkShader.cpp
        src/shaders/SkShaderBase.cpp
        src/shaders/SkTransformShader.cpp
        src/shaders/SkTriColorShader.cpp
        src/shaders/SkWorkingColorSpaceShader.cpp
        src/sksl/analysis/SkSLCanExitWithoutReturningValue.cpp
        src/sksl/analysis/SkSLCheckProgramStructure.cpp
        src/sksl/analysis/SkSLFinalizationChecks.cpp
        src/sksl/analysis/SkSLGetLoopControlFlowInfo.cpp
        src/sksl/analysis/SkSLGetLoopUnrollInfo.cpp
        src/sksl/analysis/SkSLGetReturnComplexity.cpp
        src/sksl/analysis/SkSLHasSideEffects.cpp
        src/sksl/analysis/SkSLIsConstantExpression.cpp
        src/sksl/analysis/SkSLIsDynamicallyUniformExpression.cpp
        src/sksl/analysis/SkSLIsSameExpressionTree.cpp
        src/sksl/analysis/SkSLIsTrivialExpression.cpp
        src/sksl/analysis/SkSLProgramUsage.cpp
        src/sksl/analysis/SkSLReturnsInputAlpha.cpp
        src/sksl/analysis/SkSLSwitchCaseContainsExit.cpp
        src/sksl/analysis/SkSLSymbolTableStackBuilder.cpp
        src/sksl/codegen/SkSLGLSLCodeGenerator.cpp
        src/sksl/codegen/SkSLMetalCodeGenerator.cpp
        src/sksl/codegen/SkSLPipelineStageCodeGenerator.cpp
        src/sksl/codegen/SkSLRasterPipelineBuilder.cpp
        src/sksl/codegen/SkSLRasterPipelineCodeGenerator.cpp
        src/sksl/codegen/SkSLSPIRVCodeGenerator.cpp
        src/sksl/codegen/SkSLSPIRVtoHLSL.cpp
        src/sksl/codegen/SkSLWGSLCodeGenerator.cpp
        src/sksl/ir/SkSLBinaryExpression.cpp
        src/sksl/ir/SkSLBlock.cpp
        src/sksl/ir/SkSLChildCall.cpp
        src/sksl/ir/SkSLConstructor.cpp
        src/sksl/ir/SkSLConstructorArray.cpp
        src/sksl/ir/SkSLConstructorArrayCast.cpp
        src/sksl/ir/SkSLConstructorCompound.cpp
        src/sksl/ir/SkSLConstructorCompoundCast.cpp
        src/sksl/ir/SkSLConstructorDiagonalMatrix.cpp
        src/sksl/ir/SkSLConstructorMatrixResize.cpp
        src/sksl/ir/SkSLConstructorScalarCast.cpp
        src/sksl/ir/SkSLConstructorSplat.cpp
        src/sksl/ir/SkSLConstructorStruct.cpp
        src/sksl/ir/SkSLDiscardStatement.cpp
        src/sksl/ir/SkSLDoStatement.cpp
        src/sksl/ir/SkSLExpression.cpp
        src/sksl/ir/SkSLExpressionStatement.cpp
        src/sksl/ir/SkSLExtension.cpp
        src/sksl/ir/SkSLFieldAccess.cpp
        src/sksl/ir/SkSLForStatement.cpp
        src/sksl/ir/SkSLFunctionCall.cpp
        src/sksl/ir/SkSLFunctionDeclaration.cpp
        src/sksl/ir/SkSLFunctionDefinition.cpp
        src/sksl/ir/SkSLIfStatement.cpp
        src/sksl/ir/SkSLIndexExpression.cpp
        src/sksl/ir/SkSLInterfaceBlock.cpp
        src/sksl/ir/SkSLLayout.cpp
        src/sksl/ir/SkSLLiteral.cpp
        src/sksl/ir/SkSLModifierFlags.cpp
        src/sksl/ir/SkSLModifiersDeclaration.cpp
        src/sksl/ir/SkSLPostfixExpression.cpp
        src/sksl/ir/SkSLPrefixExpression.cpp
        src/sksl/ir/SkSLProgram.cpp
        src/sksl/ir/SkSLSetting.cpp
        src/sksl/ir/SkSLStructDefinition.cpp
        src/sksl/ir/SkSLSwitchCase.cpp
        src/sksl/ir/SkSLSwitchStatement.cpp
        src/sksl/ir/SkSLSwizzle.cpp
        src/sksl/ir/SkSLSymbolTable.cpp
        src/sksl/ir/SkSLTernaryExpression.cpp
        src/sksl/ir/SkSLType.cpp
        src/sksl/ir/SkSLTypeReference.cpp
        src/sksl/ir/SkSLVarDeclarations.cpp
        src/sksl/ir/SkSLVariable.cpp
        src/sksl/ir/SkSLVariableReference.cpp
        src/sksl/SkSLAnalysis.cpp
        src/sksl/SkSLBuiltinTypes.cpp
        src/sksl/SkSLCompiler.cpp
        src/sksl/SkSLConstantFolder.cpp
        src/sksl/SkSLContext.cpp
        src/sksl/SkSLErrorReporter.cpp
        src/sksl/SkSLInliner.cpp
        src/sksl/SkSLIntrinsicList.cpp
        src/sksl/SkSLLexer.cpp
        src/sksl/SkSLMangler.cpp
        src/sksl/SkSLMemoryLayout.h
        src/sksl/SkSLModuleLoader.cpp
        src/sksl/SkSLOperator.cpp
        src/sksl/SkSLOutputStream.cpp
        src/sksl/SkSLParser.cpp
        src/sksl/SkSLPool.cpp
        src/sksl/SkSLPosition.cpp
        src/sksl/SkSLSampleUsage.cpp
        src/sksl/SkSLString.cpp
        src/sksl/SkSLThreadContext.cpp
        src/sksl/SkSLUtil.cpp
        src/sksl/tracing/SkSLDebugTracePlayer.cpp
        src/sksl/tracing/SkSLDebugTracePriv.cpp
        src/sksl/tracing/SkSLTraceHook.cpp
        src/sksl/transform/SkSLAddConstToVarModifiers.cpp
        src/sksl/transform/SkSLEliminateDeadFunctions.cpp
        src/sksl/transform/SkSLEliminateDeadGlobalVariables.cpp
        src/sksl/transform/SkSLEliminateDeadLocalVariables.cpp
        src/sksl/transform/SkSLEliminateEmptyStatements.cpp
        src/sksl/transform/SkSLEliminateUnreachableCode.cpp
        src/sksl/transform/SkSLFindAndDeclareBuiltinFunctions.cpp
        src/sksl/transform/SkSLFindAndDeclareBuiltinVariables.cpp
        src/sksl/transform/SkSLHoistSwitchVarDeclarationsAtTopLevel.cpp
        src/sksl/transform/SkSLRenamePrivateSymbols.cpp
        src/sksl/transform/SkSLReplaceConstVarsWithLiterals.cpp
        src/sksl/transform/SkSLRewriteIndexedSwizzle.cpp
        src/svg/SkSVGCanvas.cpp
        src/svg/SkSVGDevice.cpp
        src/text/GlyphRun.cpp
        src/text/SlugFromBuffer.cpp
        src/text/StrikeForGPU.cpp
        src/utils/SkAnimCodecPlayer.cpp
        src/utils/SkCamera.cpp
        src/utils/SkCanvasStack.cpp
        src/utils/SkCanvasStateUtils.cpp
        src/utils/SkCharToGlyphCache.cpp
        src/utils/SkClipStackUtils.cpp
        src/utils/SkCustomTypeface.cpp
        src/utils/SkDashPath.cpp
        src/utils/SkEventTracer.cpp
        src/utils/SkFloatToDecimal.cpp
        src/utils/SkJSON.cpp
        src/utils/SkJSONWriter.cpp
        src/utils/SkMatrix22.cpp
        src/utils/SkMultiPictureDocument.cpp
        src/utils/SkNullCanvas.cpp
        src/utils/SkNWayCanvas.cpp
        src/utils/SkOrderedFontMgr.cpp
        src/utils/SkOSPath.cpp
        src/utils/SkPaintFilterCanvas.cpp
        src/utils/SkParse.cpp
        src/utils/SkParseColor.cpp
        src/utils/SkParsePath.cpp
        src/utils/SkPatchUtils.cpp
        src/utils/SkPolyUtils.cpp
        src/utils/SkShaderUtils.cpp
        src/utils/SkShadowTessellator.cpp
        src/utils/SkShadowUtils.cpp
        src/utils/SkTextUtils.cpp
        # src/utils/SkTestCanvas.cpp
        src/xml/SkDOM.cpp
        src/xml/SkXMLParser.cpp
        src/xml/SkXMLWriter.cpp
)

if(RESKIA_ENABLE_AVIF)
    list(APPEND SOURCE_FILES src/codec/SkAvifCodec.cpp)
endif()

if(RESKIA_ENABLE_JPEGXL)
    list(APPEND SOURCE_FILES src/codec/SkJpegxlCodec.cpp)
endif()

if(RESKIA_ENABLE_RAW)
    if(EXISTS "${RESKIA_ROOT_DIR}/third_party/src/dng_sdk/source/dng_host.h"
            AND EXISTS "${RESKIA_ROOT_DIR}/third_party/src/piex/src/piex.h")
        list(APPEND SOURCE_FILES src/codec/SkRawCodec.cpp)
        file(GLOB DNG_SDK_SOURCES "${RESKIA_ROOT_DIR}/third_party/src/dng_sdk/source/*.cpp")
        list(FILTER DNG_SDK_SOURCES EXCLUDE REGEX ".*/dng_xmp(_sdk)?\\.cpp$")
        list(FILTER DNG_SDK_SOURCES EXCLUDE REGEX ".*/dng_validate\\.cpp$")
        list(APPEND SOURCE_FILES ${DNG_SDK_SOURCES})
        list(APPEND SOURCE_FILES
                "${RESKIA_ROOT_DIR}/third_party/src/piex/src/binary_parse/cached_paged_byte_array.cc"
                "${RESKIA_ROOT_DIR}/third_party/src/piex/src/binary_parse/range_checked_byte_ptr.cc"
                "${RESKIA_ROOT_DIR}/third_party/src/piex/src/image_type_recognition/image_type_recognition_lite.cc"
                "${RESKIA_ROOT_DIR}/third_party/src/piex/src/piex.cc"
                "${RESKIA_ROOT_DIR}/third_party/src/piex/src/piex_cr3.cc"
                "${RESKIA_ROOT_DIR}/third_party/src/piex/src/tiff_directory/tiff_directory.cc"
                "${RESKIA_ROOT_DIR}/third_party/src/piex/src/tiff_parser.cc"
        )
    else()
        message(WARNING "RESKIA_ENABLE_RAW=ON ですが third_party/src/dng_sdk または third_party/src/piex が未配置のため SkRawCodec.cpp は未追加です。")
    endif()
endif()

if(RESKIA_ENABLE_GIF)
    if(EXISTS "${RESKIA_ROOT_DIR}/third_party/src/wuffs/release/c/wuffs-v0.3.c")
        list(APPEND SOURCE_FILES src/codec/SkWuffsCodec.cpp)
        list(APPEND SOURCE_FILES "${RESKIA_ROOT_DIR}/third_party/src/wuffs/release/c/wuffs-v0.3.c")
    else()
        message(WARNING "RESKIA_ENABLE_GIF=ON ですが third_party/src/wuffs/release/c/wuffs-v0.3.c が未配置のため SkWuffsCodec.cpp は未追加です。")
    endif()
endif()

if(RESKIA_ENABLE_PDF)
    list(APPEND SOURCE_FILES
            src/pdf/SkClusterator.cpp
            src/pdf/SkDeflate.cpp
            src/pdf/SkJpegInfo_none.cpp
            src/pdf/SkKeyedImage.cpp
            src/pdf/SkPDFBitmap.cpp
            src/pdf/SkPDFDevice.cpp
            src/pdf/SkPDFDocument.cpp
            src/pdf/SkPDFFont.cpp
            src/pdf/SkPDFFormXObject.cpp
            src/pdf/SkPDFGradientShader.cpp
            src/pdf/SkPDFGraphicStackState.cpp
            src/pdf/SkPDFGraphicState.cpp
            src/pdf/SkPDFMakeCIDGlyphWidthsArray.cpp
            src/pdf/SkPDFMakeToUnicodeCmap.cpp
            src/pdf/SkPDFMetadata.cpp
            src/pdf/SkPDFResourceDict.cpp
            src/pdf/SkPDFShader.cpp
            src/pdf/SkPDFSubsetFont.cpp
            src/pdf/SkPDFTag.cpp
            src/pdf/SkPDFType1Font.cpp
            src/pdf/SkPDFTypes.cpp
            src/pdf/SkPDFUtils.cpp
    )
endif()

if(RESKIA_ENABLE_SKOTTIE)
    if(NOT APPLE)
        message(FATAL_ERROR "RESKIA_ENABLE_SKOTTIE=ON は現在 APPLE のみ対応です。")
    endif()
    if(NOT EXISTS "${PROJECT_SOURCE_DIR}/modules/sksg/sksg.gni")
        message(FATAL_ERROR "RESKIA_ENABLE_SKOTTIE=ON ですが modules/sksg/sksg.gni が見つかりません。Phase 1 の同期を実施してください。")
    endif()
    if(NOT EXISTS "${PROJECT_SOURCE_DIR}/modules/skottie/skottie.gni")
        message(FATAL_ERROR "RESKIA_ENABLE_SKOTTIE=ON ですが modules/skottie/skottie.gni が見つかりません。Phase 1 の同期を実施してください。")
    endif()

    set(_reskia_skottie_sources "")
    file(STRINGS "${PROJECT_SOURCE_DIR}/modules/sksg/sksg.gni" _reskia_sksg_gni_lines REGEX "\\$_modules/.+")
    file(STRINGS "${PROJECT_SOURCE_DIR}/modules/skottie/skottie.gni" _reskia_skottie_gni_lines REGEX "\\$_modules/.+")

    foreach(_reskia_gni_line IN LISTS _reskia_sksg_gni_lines _reskia_skottie_gni_lines)
        string(REGEX MATCH "\\$_modules/[^\" ]+" _reskia_gni_path "${_reskia_gni_line}")
        if(_reskia_gni_path)
            string(REPLACE "$_modules/" "modules/" _reskia_module_path "${_reskia_gni_path}")
            list(APPEND _reskia_skottie_sources "${_reskia_module_path}")
        endif()
    endforeach()

    list(REMOVE_DUPLICATES _reskia_skottie_sources)
    list(APPEND SOURCE_FILES ${_reskia_skottie_sources})
endif()

if(RESKIA_ENABLE_JPEG_ENCODER)
    list(APPEND SOURCE_FILES
            src/encode/SkJPEGWriteUtility.cpp
            src/encode/SkJpegEncoderImpl.cpp
    )
else()
    list(APPEND SOURCE_FILES src/encode/SkJpegEncoder_none.cpp)
endif()

if(RESKIA_ENABLE_WEBP_ENCODER)
    if(EXISTS "${PROJECT_SOURCE_DIR}/src/encode/SkWebpEncoderImpl.cpp")
        list(APPEND SOURCE_FILES src/encode/SkWebpEncoderImpl.cpp)
    else()
        message(WARNING "RESKIA_ENABLE_WEBP_ENCODER=ON ですが SkWebpEncoderImpl.cpp が見つからないため none 実装を使用します。")
        list(APPEND SOURCE_FILES src/encode/SkWebpEncoder_none.cpp)
    endif()
else()
    list(APPEND SOURCE_FILES src/encode/SkWebpEncoder_none.cpp)
endif()
