option(RESKIA_BUILD_TESTS "Build test_c_skia target" OFF)
if(RESKIA_BUILD_TESTS)
    enable_testing()
    add_executable(test_c_skia test/test.cpp )
    target_include_directories(test_c_skia PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(APPLE)
        find_library(CORE_FOUNDATION CoreFoundation)
        find_library(CORE_TEXT CoreText)
        if(RESKIA_ENABLE_FONTCONFIG_CAPI AND RESKIA_FONTCONFIG_LIBRARY)
            target_link_libraries(test_c_skia reskia "-framework CoreFoundation" "-framework CoreText" ${CORE_FOUNDATION} ${CORE_TEXT} "${RESKIA_FONTCONFIG_LIBRARY}")
        else()
            target_link_libraries(test_c_skia reskia "-framework CoreFoundation" "-framework CoreText" ${CORE_FOUNDATION} ${CORE_TEXT})
        endif()
    elseif (WIN32)
        target_link_libraries(test_c_skia reskia)
    endif ()
    add_test(NAME c_skia_test COMMAND test_c_skia)

    add_executable(test_phase_c_callback_smoke test/test_phase_c_callback_smoke.cpp)
    target_include_directories(test_phase_c_callback_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_phase_c_callback_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_phase_c_callback_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_phase_c_callback_smoke COMMAND test_phase_c_callback_smoke)

    add_executable(test_phase_d_async_read_smoke test/test_phase_d_async_read_smoke.cpp)
    target_include_directories(test_phase_d_async_read_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_phase_d_async_read_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_phase_d_async_read_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_phase_d_async_read_smoke COMMAND test_phase_d_async_read_smoke)

    add_executable(test_codec_smoke test/test_codec_smoke.cpp)
    target_include_directories(test_codec_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_codec_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_codec_smoke reskia ${RESKIA_DEP_LIBS})
    if(RESKIA_ENABLE_AVIF)
        target_compile_definitions(test_codec_smoke PRIVATE RESKIA_TEST_ENABLE_AVIF=1)
    endif()
    if(RESKIA_ENABLE_JPEGXL)
        target_compile_definitions(test_codec_smoke PRIVATE RESKIA_TEST_ENABLE_JPEGXL=1)
    endif()
    if(RESKIA_ENABLE_GIF)
        target_compile_definitions(test_codec_smoke PRIVATE RESKIA_TEST_ENABLE_GIF=1)
    endif()
    if(RESKIA_ENABLE_RAW)
        target_compile_definitions(test_codec_smoke PRIVATE RESKIA_TEST_ENABLE_RAW=1)
    endif()
    if(RESKIA_ENABLE_JPEG_ENCODER)
        target_compile_definitions(test_codec_smoke PRIVATE RESKIA_TEST_ENABLE_JPEG_ENCODER=1)
    endif()
    if(RESKIA_ENABLE_WEBP_ENCODER)
        target_compile_definitions(test_codec_smoke PRIVATE RESKIA_TEST_ENABLE_WEBP_ENCODER=1)
    endif()
    if(APPLE)
        target_compile_definitions(test_codec_smoke PRIVATE RESKIA_TEST_ENABLE_OPEN_TYPE_SVG=1)
    endif()
    add_test(NAME c_skia_codec_smoke COMMAND test_codec_smoke)

    add_executable(test_canvas_invalid_input_smoke test/test_canvas_invalid_input_smoke.cpp)
    target_include_directories(test_canvas_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_canvas_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_canvas_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_canvas_invalid_input_smoke COMMAND test_canvas_invalid_input_smoke)

    add_executable(test_image_surface_invalid_input_smoke test/test_image_surface_invalid_input_smoke.cpp)
    target_include_directories(test_image_surface_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_image_surface_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_image_surface_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_image_surface_invalid_input_smoke COMMAND test_image_surface_invalid_input_smoke)

    add_executable(test_bitmap_invalid_input_smoke test/test_bitmap_invalid_input_smoke.cpp)
    target_include_directories(test_bitmap_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_bitmap_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_bitmap_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_bitmap_invalid_input_smoke COMMAND test_bitmap_invalid_input_smoke)

    add_executable(test_path_invalid_input_smoke test/test_path_invalid_input_smoke.cpp)
    target_include_directories(test_path_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_path_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_path_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_path_invalid_input_smoke COMMAND test_path_invalid_input_smoke)

    add_executable(test_paint_invalid_input_smoke test/test_paint_invalid_input_smoke.cpp)
    target_include_directories(test_paint_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_paint_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_paint_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_paint_invalid_input_smoke COMMAND test_paint_invalid_input_smoke)

    add_executable(test_rect_rrect_invalid_input_smoke test/test_rect_rrect_invalid_input_smoke.cpp)
    target_include_directories(test_rect_rrect_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_rect_rrect_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_rect_rrect_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_rect_rrect_invalid_input_smoke COMMAND test_rect_rrect_invalid_input_smoke)

    add_executable(test_image_info_invalid_input_smoke test/test_image_info_invalid_input_smoke.cpp)
    target_include_directories(test_image_info_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_image_info_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_image_info_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_image_info_invalid_input_smoke COMMAND test_image_info_invalid_input_smoke)

    add_executable(test_data_invalid_input_smoke test/test_data_invalid_input_smoke.cpp)
    target_include_directories(test_data_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_data_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_data_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_data_invalid_input_smoke COMMAND test_data_invalid_input_smoke)

    add_executable(test_stream_invalid_input_smoke test/test_stream_invalid_input_smoke.cpp)
    target_include_directories(test_stream_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_stream_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_stream_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_stream_invalid_input_smoke COMMAND test_stream_invalid_input_smoke)

    add_executable(test_wstream_invalid_input_smoke test/test_wstream_invalid_input_smoke.cpp)
    target_include_directories(test_wstream_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_wstream_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_wstream_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_wstream_invalid_input_smoke COMMAND test_wstream_invalid_input_smoke)

    add_executable(test_stream_derived_invalid_input_smoke test/test_stream_derived_invalid_input_smoke.cpp)
    target_include_directories(test_stream_derived_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_stream_derived_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_stream_derived_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_stream_derived_invalid_input_smoke COMMAND test_stream_derived_invalid_input_smoke)

    add_executable(test_color_info_space_invalid_input_smoke test/test_color_info_space_invalid_input_smoke.cpp)
    target_include_directories(test_color_info_space_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_color_info_space_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_color_info_space_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_color_info_space_invalid_input_smoke COMMAND test_color_info_space_invalid_input_smoke)

    add_executable(test_path_effect_invalid_input_smoke test/test_path_effect_invalid_input_smoke.cpp)
    target_include_directories(test_path_effect_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_path_effect_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_path_effect_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_path_effect_invalid_input_smoke COMMAND test_path_effect_invalid_input_smoke)

    add_executable(test_color_filter_invalid_input_smoke test/test_color_filter_invalid_input_smoke.cpp)
    target_include_directories(test_color_filter_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_color_filter_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_color_filter_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_color_filter_invalid_input_smoke COMMAND test_color_filter_invalid_input_smoke)

    add_executable(test_color_values_invalid_input_smoke test/test_color_values_invalid_input_smoke.cpp)
    target_include_directories(test_color_values_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_color_values_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_color_values_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_color_values_invalid_input_smoke COMMAND test_color_values_invalid_input_smoke)

    add_executable(test_color_matrix_filter_invalid_input_smoke test/test_color_matrix_filter_invalid_input_smoke.cpp)
    target_include_directories(test_color_matrix_filter_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_color_matrix_filter_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_color_matrix_filter_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_color_matrix_filter_invalid_input_smoke COMMAND test_color_matrix_filter_invalid_input_smoke)

    add_executable(test_color_core_invalid_input_smoke test/test_color_core_invalid_input_smoke.cpp)
    target_include_directories(test_color_core_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_color_core_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_color_core_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_color_core_invalid_input_smoke COMMAND test_color_core_invalid_input_smoke)

    add_executable(test_contour_path_measure_invalid_input_smoke test/test_contour_path_measure_invalid_input_smoke.cpp)
    target_include_directories(test_contour_path_measure_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_contour_path_measure_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_contour_path_measure_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_contour_path_measure_invalid_input_smoke COMMAND test_contour_path_measure_invalid_input_smoke)

    add_executable(test_data_table_invalid_input_smoke test/test_data_table_invalid_input_smoke.cpp)
    target_include_directories(test_data_table_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_data_table_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_data_table_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_data_table_invalid_input_smoke COMMAND test_data_table_invalid_input_smoke)

    add_executable(test_color_table_invalid_input_smoke test/test_color_table_invalid_input_smoke.cpp)
    target_include_directories(test_color_table_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_color_table_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_color_table_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_color_table_invalid_input_smoke COMMAND test_color_table_invalid_input_smoke)

    add_executable(test_mask_filter_invalid_input_smoke test/test_mask_filter_invalid_input_smoke.cpp)
    target_include_directories(test_mask_filter_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_mask_filter_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_mask_filter_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_mask_filter_invalid_input_smoke COMMAND test_mask_filter_invalid_input_smoke)

    add_executable(test_mask_invalid_input_smoke test/test_mask_invalid_input_smoke.cpp)
    target_include_directories(test_mask_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_mask_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_mask_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_mask_invalid_input_smoke COMMAND test_mask_invalid_input_smoke)

    add_executable(test_matrix_invalid_input_smoke test/test_matrix_invalid_input_smoke.cpp)
    target_include_directories(test_matrix_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_matrix_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_matrix_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_matrix_invalid_input_smoke COMMAND test_matrix_invalid_input_smoke)

    add_executable(test_m44_invalid_input_smoke test/test_m44_invalid_input_smoke.cpp)
    target_include_directories(test_m44_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_m44_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_m44_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_m44_invalid_input_smoke COMMAND test_m44_invalid_input_smoke)

    add_executable(test_vector_invalid_input_smoke test/test_vector_invalid_input_smoke.cpp)
    target_include_directories(test_vector_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_vector_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_vector_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_vector_invalid_input_smoke COMMAND test_vector_invalid_input_smoke)

    add_executable(test_vertices_invalid_input_smoke test/test_vertices_invalid_input_smoke.cpp)
    target_include_directories(test_vertices_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_vertices_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_vertices_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_vertices_invalid_input_smoke COMMAND test_vertices_invalid_input_smoke)

    add_executable(test_font_style_set_invalid_input_smoke test/test_font_style_set_invalid_input_smoke.cpp)
    target_include_directories(test_font_style_set_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_font_style_set_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_font_style_set_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_font_style_set_invalid_input_smoke COMMAND test_font_style_set_invalid_input_smoke)

    if(APPLE AND TARGET svg AND TARGET skshaper AND TARGET skunicode)
        add_executable(test_shaping_smoke test/test_shaping_smoke.cpp)
        target_include_directories(test_shaping_smoke PRIVATE
                ${RESKIA_PUBLIC_INCLUDE_DIRS}
        )
        if(RESKIA_DEP_LINK_DIRS)
            target_link_directories(test_shaping_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
        endif()
        target_link_libraries(test_shaping_smoke reskia ${RESKIA_DEP_LIBS})
        add_test(NAME c_skia_shaping_smoke COMMAND test_shaping_smoke)
    endif()

    if(RESKIA_ENABLE_PDF)
        add_executable(test_pdf_smoke test/test_pdf_smoke.cpp)
        target_include_directories(test_pdf_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
        if(RESKIA_DEP_LINK_DIRS)
            target_link_directories(test_pdf_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
        endif()
        target_link_libraries(test_pdf_smoke reskia ${RESKIA_DEP_LIBS})
        add_test(NAME c_skia_pdf_smoke COMMAND test_pdf_smoke)
    endif()

    if(RESKIA_ENABLE_SKOTTIE)
        add_executable(test_skottie_smoke test/test_skottie_smoke.cpp)
        target_include_directories(test_skottie_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
        if(RESKIA_DEP_LINK_DIRS)
            target_link_directories(test_skottie_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
        endif()
        target_link_libraries(test_skottie_smoke reskia ${RESKIA_DEP_LIBS})
        add_test(NAME c_skia_skottie_smoke COMMAND test_skottie_smoke)
    endif()

    if(RESKIA_ENABLE_SKSG)
        add_executable(test_sksg_smoke test/test_sksg_smoke.cpp)
        target_include_directories(test_sksg_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
        if(RESKIA_DEP_LINK_DIRS)
            target_link_directories(test_sksg_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
        endif()
        target_link_libraries(test_sksg_smoke reskia ${RESKIA_DEP_LIBS})
        add_test(NAME c_skia_sksg_smoke COMMAND test_sksg_smoke)

        add_executable(test_sksg_capi_smoke test/test_sksg_capi_smoke.cpp)
        target_include_directories(test_sksg_capi_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
        if(RESKIA_DEP_LINK_DIRS)
            target_link_directories(test_sksg_capi_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
        endif()
        target_link_libraries(test_sksg_capi_smoke reskia ${RESKIA_DEP_LIBS})
        add_test(NAME c_skia_sksg_capi_smoke COMMAND test_sksg_capi_smoke)
    endif()

    if(RESKIA_ENABLE_SKPARAGRAPH AND TARGET skshaper AND TARGET skunicode)
        add_executable(test_skparagraph_smoke test/test_skparagraph_smoke.cpp)
        target_include_directories(test_skparagraph_smoke PRIVATE
                ${RESKIA_PUBLIC_INCLUDE_DIRS}
        )
        if(RESKIA_DEP_LINK_DIRS)
            target_link_directories(test_skparagraph_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
        endif()
        target_link_libraries(test_skparagraph_smoke reskia ${RESKIA_DEP_LIBS})
        add_test(NAME c_skia_skparagraph_smoke COMMAND test_skparagraph_smoke)
    endif()

    if(APPLE AND RESKIA_ENABLE_GPU_GANESH AND RESKIA_ENABLE_GPU_METAL)
        add_executable(test_gpu_surface_capi_smoke test/test_gpu_surface_capi_smoke.mm)
        target_include_directories(test_gpu_surface_capi_smoke PRIVATE
                ${RESKIA_PUBLIC_INCLUDE_DIRS}
        )
        if(RESKIA_DEP_LINK_DIRS)
            target_link_directories(test_gpu_surface_capi_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
        endif()
        target_link_libraries(test_gpu_surface_capi_smoke reskia ${RESKIA_DEP_LIBS} "-framework Metal")
        add_test(NAME c_skia_gpu_surface_capi_smoke COMMAND test_gpu_surface_capi_smoke)
    endif()

    if(APPLE AND RESKIA_ENABLE_GPU_METAL AND (RESKIA_ENABLE_GPU_GANESH OR RESKIA_ENABLE_GPU_GRAPHITE))
        add_executable(test_gpu_context_capi_smoke test/test_gpu_context_capi_smoke.mm)
        target_include_directories(test_gpu_context_capi_smoke PRIVATE
                ${RESKIA_PUBLIC_INCLUDE_DIRS}
        )
        if(RESKIA_DEP_LINK_DIRS)
            target_link_directories(test_gpu_context_capi_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
        endif()
        target_compile_definitions(test_gpu_context_capi_smoke PRIVATE
                RESKIA_TEST_GPU_GANESH=$<BOOL:${RESKIA_ENABLE_GPU_GANESH}>
                RESKIA_TEST_GPU_GRAPHITE=$<BOOL:${RESKIA_ENABLE_GPU_GRAPHITE}>
        )
        target_link_libraries(test_gpu_context_capi_smoke reskia ${RESKIA_DEP_LIBS} "-framework Metal")
        add_test(NAME c_skia_gpu_context_capi_smoke COMMAND test_gpu_context_capi_smoke)
    endif()
endif()
