option(RESKIA_BUILD_TESTS "Build test_c_skia target" OFF)
if(RESKIA_BUILD_TESTS)
    enable_testing()
    add_executable(test_c_skia test/test.cpp )
    target_include_directories(test_c_skia PRIVATE "${PROJECT_SOURCE_DIR}" "${PROJECT_SOURCE_DIR}/_include")
    if(APPLE)
        find_library(CORE_FOUNDATION CoreFoundation)
        find_library(CORE_TEXT CoreText)
        target_link_libraries(test_c_skia reskia "-framework CoreFoundation" "-framework CoreText" ${CORE_FOUNDATION} ${CORE_TEXT} fontconfig)
    elseif (WIN32)
        target_link_libraries(test_c_skia reskia)
    endif ()
    add_test(NAME c_skia_test COMMAND test_c_skia)

    add_executable(test_codec_smoke test/test_codec_smoke.cpp)
    target_include_directories(test_codec_smoke PRIVATE "${PROJECT_SOURCE_DIR}" "${PROJECT_SOURCE_DIR}/_include")
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_codec_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_codec_smoke reskia ${RESKIA_DEP_LIBS})
    if(RESKIA_ENABLE_AVIF)
        target_compile_definitions(test_codec_smoke PRIVATE RESKIA_TEST_ENABLE_AVIF=1)
    endif()
    if(RESKIA_ENABLE_JPEGXL)
        target_compile_definitions(test_codec_smoke PRIVATE RESKIA_TEST_ENABLE_JPEGXL=1)
    endif()
    if(RESKIA_ENABLE_GIF)
        target_compile_definitions(test_codec_smoke PRIVATE RESKIA_TEST_ENABLE_GIF=1)
    endif()
    if(RESKIA_ENABLE_RAW)
        target_compile_definitions(test_codec_smoke PRIVATE RESKIA_TEST_ENABLE_RAW=1)
    endif()
    if(RESKIA_ENABLE_JPEG_ENCODER)
        target_compile_definitions(test_codec_smoke PRIVATE RESKIA_TEST_ENABLE_JPEG_ENCODER=1)
    endif()
    if(RESKIA_ENABLE_WEBP_ENCODER)
        target_compile_definitions(test_codec_smoke PRIVATE RESKIA_TEST_ENABLE_WEBP_ENCODER=1)
    endif()
    if(APPLE)
        target_compile_definitions(test_codec_smoke PRIVATE RESKIA_TEST_ENABLE_OPEN_TYPE_SVG=1)
    endif()
    add_test(NAME c_skia_codec_smoke COMMAND test_codec_smoke)

    if(RESKIA_ENABLE_PDF)
        add_executable(test_pdf_smoke test/test_pdf_smoke.cpp)
        target_include_directories(test_pdf_smoke PRIVATE "${PROJECT_SOURCE_DIR}" "${PROJECT_SOURCE_DIR}/_include")
        if(RESKIA_DEP_LINK_DIRS)
            target_link_directories(test_pdf_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
        endif()
        target_link_libraries(test_pdf_smoke reskia ${RESKIA_DEP_LIBS})
        add_test(NAME c_skia_pdf_smoke COMMAND test_pdf_smoke)
    endif()
endif()
