option(RESKIA_BUILD_TESTS "Build test_c_skia target" OFF)
if(RESKIA_BUILD_TESTS)
    enable_testing()
    add_executable(test_c_skia test/test.cpp )
    target_include_directories(test_c_skia PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(APPLE)
        find_library(CORE_FOUNDATION CoreFoundation)
        find_library(CORE_TEXT CoreText)
        if(RESKIA_ENABLE_FONTCONFIG_CAPI AND RESKIA_FONTCONFIG_LIBRARY)
            target_link_libraries(test_c_skia reskia "-framework CoreFoundation" "-framework CoreText" ${CORE_FOUNDATION} ${CORE_TEXT} "${RESKIA_FONTCONFIG_LIBRARY}")
        else()
            target_link_libraries(test_c_skia reskia "-framework CoreFoundation" "-framework CoreText" ${CORE_FOUNDATION} ${CORE_TEXT})
        endif()
    elseif (WIN32)
        target_link_libraries(test_c_skia reskia)
    endif ()
    add_test(NAME c_skia_test COMMAND test_c_skia)

    add_executable(test_phase_c_callback_smoke test/test_phase_c_callback_smoke.cpp)
    target_include_directories(test_phase_c_callback_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_phase_c_callback_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_phase_c_callback_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_phase_c_callback_smoke COMMAND test_phase_c_callback_smoke)

    add_executable(test_phase_d_async_read_smoke test/test_phase_d_async_read_smoke.cpp)
    target_include_directories(test_phase_d_async_read_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_phase_d_async_read_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_phase_d_async_read_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_phase_d_async_read_smoke COMMAND test_phase_d_async_read_smoke)

    add_executable(test_codec_smoke test/test_codec_smoke.cpp)
    target_include_directories(test_codec_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_codec_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_codec_smoke reskia ${RESKIA_DEP_LIBS})
    if(RESKIA_ENABLE_AVIF)
        target_compile_definitions(test_codec_smoke PRIVATE RESKIA_TEST_ENABLE_AVIF=1)
    endif()
    if(RESKIA_ENABLE_JPEGXL)
        target_compile_definitions(test_codec_smoke PRIVATE RESKIA_TEST_ENABLE_JPEGXL=1)
    endif()
    if(RESKIA_ENABLE_GIF)
        target_compile_definitions(test_codec_smoke PRIVATE RESKIA_TEST_ENABLE_GIF=1)
    endif()
    if(RESKIA_ENABLE_RAW)
        target_compile_definitions(test_codec_smoke PRIVATE RESKIA_TEST_ENABLE_RAW=1)
    endif()
    if(RESKIA_ENABLE_JPEG_ENCODER)
        target_compile_definitions(test_codec_smoke PRIVATE RESKIA_TEST_ENABLE_JPEG_ENCODER=1)
    endif()
    if(RESKIA_ENABLE_WEBP_ENCODER)
        target_compile_definitions(test_codec_smoke PRIVATE RESKIA_TEST_ENABLE_WEBP_ENCODER=1)
    endif()
    if(APPLE)
        target_compile_definitions(test_codec_smoke PRIVATE RESKIA_TEST_ENABLE_OPEN_TYPE_SVG=1)
    endif()
    add_test(NAME c_skia_codec_smoke COMMAND test_codec_smoke)

    add_executable(test_canvas_invalid_input_smoke test/test_canvas_invalid_input_smoke.cpp)
    target_include_directories(test_canvas_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_canvas_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_canvas_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_canvas_invalid_input_smoke COMMAND test_canvas_invalid_input_smoke)

    add_executable(test_image_surface_invalid_input_smoke test/test_image_surface_invalid_input_smoke.cpp)
    target_include_directories(test_image_surface_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_image_surface_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_image_surface_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_image_surface_invalid_input_smoke COMMAND test_image_surface_invalid_input_smoke)

    add_executable(test_surface_props_surfaces_invalid_input_smoke test/test_surface_props_surfaces_invalid_input_smoke.cpp)
    target_include_directories(test_surface_props_surfaces_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_surface_props_surfaces_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_surface_props_surfaces_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_surface_props_surfaces_invalid_input_smoke COMMAND test_surface_props_surfaces_invalid_input_smoke)

    add_executable(test_bitmap_invalid_input_smoke test/test_bitmap_invalid_input_smoke.cpp)
    target_include_directories(test_bitmap_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_bitmap_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_bitmap_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_bitmap_invalid_input_smoke COMMAND test_bitmap_invalid_input_smoke)

    add_executable(test_path_invalid_input_smoke test/test_path_invalid_input_smoke.cpp)
    target_include_directories(test_path_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_path_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_path_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_path_invalid_input_smoke COMMAND test_path_invalid_input_smoke)

    add_executable(test_parse_utils_smoke test/test_parse_utils_smoke.cpp)
    target_include_directories(test_parse_utils_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_parse_utils_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_parse_utils_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_parse_utils_smoke COMMAND test_parse_utils_smoke)

    add_executable(test_text_shadow_utils_smoke test/test_text_shadow_utils_smoke.cpp)
    target_include_directories(test_text_shadow_utils_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_text_shadow_utils_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_text_shadow_utils_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_text_shadow_utils_smoke COMMAND test_text_shadow_utils_smoke)

    add_executable(test_canvas_utils_smoke test/test_canvas_utils_smoke.cpp)
    target_include_directories(test_canvas_utils_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_canvas_utils_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_canvas_utils_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_canvas_utils_smoke COMMAND test_canvas_utils_smoke)

    add_executable(test_custom_typeface_utils_smoke test/test_custom_typeface_utils_smoke.cpp)
    target_include_directories(test_custom_typeface_utils_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_custom_typeface_utils_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_custom_typeface_utils_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_custom_typeface_utils_smoke COMMAND test_custom_typeface_utils_smoke)

    add_executable(test_ordered_font_mgr_utils_smoke test/test_ordered_font_mgr_utils_smoke.cpp)
    target_include_directories(test_ordered_font_mgr_utils_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_ordered_font_mgr_utils_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_ordered_font_mgr_utils_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_ordered_font_mgr_utils_smoke COMMAND test_ordered_font_mgr_utils_smoke)

    add_executable(test_animated_image_utils_smoke test/test_animated_image_utils_smoke.cpp)
    target_include_directories(test_animated_image_utils_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_animated_image_utils_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_animated_image_utils_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_animated_image_utils_smoke COMMAND test_animated_image_utils_smoke)

    add_executable(test_camera_utils_smoke test/test_camera_utils_smoke.cpp)
    target_include_directories(test_camera_utils_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_camera_utils_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_camera_utils_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_camera_utils_smoke COMMAND test_camera_utils_smoke)

    add_executable(test_event_paint_filter_utils_smoke test/test_event_paint_filter_utils_smoke.cpp)
    target_include_directories(test_event_paint_filter_utils_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_event_paint_filter_utils_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_event_paint_filter_utils_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_event_paint_filter_utils_smoke COMMAND test_event_paint_filter_utils_smoke)

    if(RESKIA_ENABLE_FONTCONFIG_CAPI)
        add_executable(test_font_config_interface_utils_smoke test/test_font_config_interface_utils_smoke.cpp)
        target_include_directories(test_font_config_interface_utils_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
        if(RESKIA_DEP_LINK_DIRS)
            target_link_directories(test_font_config_interface_utils_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
        endif()
        target_link_libraries(test_font_config_interface_utils_smoke reskia ${RESKIA_DEP_LIBS})
        add_test(NAME c_skia_font_config_interface_utils_smoke COMMAND test_font_config_interface_utils_smoke)
    endif()

    add_executable(test_path_builder_invalid_input_smoke test/test_path_builder_invalid_input_smoke.cpp)
    target_include_directories(test_path_builder_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_path_builder_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_path_builder_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_path_builder_invalid_input_smoke COMMAND test_path_builder_invalid_input_smoke)

    add_executable(test_op_builder_invalid_input_smoke test/test_op_builder_invalid_input_smoke.cpp)
    target_include_directories(test_op_builder_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_op_builder_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_op_builder_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_op_builder_invalid_input_smoke COMMAND test_op_builder_invalid_input_smoke)

    add_executable(test_paint_invalid_input_smoke test/test_paint_invalid_input_smoke.cpp)
    target_include_directories(test_paint_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_paint_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_paint_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_paint_invalid_input_smoke COMMAND test_paint_invalid_input_smoke)

    add_executable(test_rect_rrect_invalid_input_smoke test/test_rect_rrect_invalid_input_smoke.cpp)
    target_include_directories(test_rect_rrect_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_rect_rrect_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_rect_rrect_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_rect_rrect_invalid_input_smoke COMMAND test_rect_rrect_invalid_input_smoke)

    add_executable(test_image_info_invalid_input_smoke test/test_image_info_invalid_input_smoke.cpp)
    target_include_directories(test_image_info_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_image_info_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_image_info_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_image_info_invalid_input_smoke COMMAND test_image_info_invalid_input_smoke)

    add_executable(test_data_invalid_input_smoke test/test_data_invalid_input_smoke.cpp)
    target_include_directories(test_data_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_data_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_data_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_data_invalid_input_smoke COMMAND test_data_invalid_input_smoke)

    add_executable(test_document_invalid_input_smoke test/test_document_invalid_input_smoke.cpp)
    target_include_directories(test_document_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_document_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_document_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_document_invalid_input_smoke COMMAND test_document_invalid_input_smoke)

    add_executable(test_stream_invalid_input_smoke test/test_stream_invalid_input_smoke.cpp)
    target_include_directories(test_stream_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_stream_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_stream_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_stream_invalid_input_smoke COMMAND test_stream_invalid_input_smoke)

    add_executable(test_wstream_invalid_input_smoke test/test_wstream_invalid_input_smoke.cpp)
    target_include_directories(test_wstream_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_wstream_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_wstream_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_wstream_invalid_input_smoke COMMAND test_wstream_invalid_input_smoke)

    add_executable(test_stream_derived_invalid_input_smoke test/test_stream_derived_invalid_input_smoke.cpp)
    target_include_directories(test_stream_derived_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_stream_derived_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_stream_derived_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_stream_derived_invalid_input_smoke COMMAND test_stream_derived_invalid_input_smoke)

    add_executable(test_file_stream_invalid_input_smoke test/test_file_stream_invalid_input_smoke.cpp)
    target_include_directories(test_file_stream_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_file_stream_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_file_stream_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_file_stream_invalid_input_smoke COMMAND test_file_stream_invalid_input_smoke)

    add_executable(test_color_info_space_invalid_input_smoke test/test_color_info_space_invalid_input_smoke.cpp)
    target_include_directories(test_color_info_space_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_color_info_space_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_color_info_space_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_color_info_space_invalid_input_smoke COMMAND test_color_info_space_invalid_input_smoke)

    add_executable(test_path_effect_invalid_input_smoke test/test_path_effect_invalid_input_smoke.cpp)
    target_include_directories(test_path_effect_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_path_effect_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_path_effect_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_path_effect_invalid_input_smoke COMMAND test_path_effect_invalid_input_smoke)

    add_executable(test_color_filter_invalid_input_smoke test/test_color_filter_invalid_input_smoke.cpp)
    target_include_directories(test_color_filter_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_color_filter_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_color_filter_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_color_filter_invalid_input_smoke COMMAND test_color_filter_invalid_input_smoke)

    add_executable(test_color_values_invalid_input_smoke test/test_color_values_invalid_input_smoke.cpp)
    target_include_directories(test_color_values_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_color_values_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_color_values_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_color_values_invalid_input_smoke COMMAND test_color_values_invalid_input_smoke)

    add_executable(test_color_matrix_filter_invalid_input_smoke test/test_color_matrix_filter_invalid_input_smoke.cpp)
    target_include_directories(test_color_matrix_filter_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_color_matrix_filter_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_color_matrix_filter_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_color_matrix_filter_invalid_input_smoke COMMAND test_color_matrix_filter_invalid_input_smoke)

    add_executable(test_color_core_invalid_input_smoke test/test_color_core_invalid_input_smoke.cpp)
    target_include_directories(test_color_core_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_color_core_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_color_core_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_color_core_invalid_input_smoke COMMAND test_color_core_invalid_input_smoke)

    add_executable(test_enum_capabilities_graphics_invalid_input_smoke test/test_enum_capabilities_graphics_invalid_input_smoke.cpp)
    target_include_directories(test_enum_capabilities_graphics_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_enum_capabilities_graphics_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_enum_capabilities_graphics_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_enum_capabilities_graphics_invalid_input_smoke COMMAND test_enum_capabilities_graphics_invalid_input_smoke)

    add_executable(test_value_icc_high_contrast_invalid_input_smoke test/test_value_icc_high_contrast_invalid_input_smoke.cpp)
    target_include_directories(test_value_icc_high_contrast_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_value_icc_high_contrast_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_value_icc_high_contrast_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_value_icc_high_contrast_invalid_input_smoke COMMAND test_value_icc_high_contrast_invalid_input_smoke)

    add_executable(test_value_transform_string_stroke_trace_invalid_input_smoke test/test_value_transform_string_stroke_trace_invalid_input_smoke.cpp)
    target_include_directories(test_value_transform_string_stroke_trace_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_value_transform_string_stroke_trace_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_value_transform_string_stroke_trace_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_value_transform_string_stroke_trace_invalid_input_smoke COMMAND test_value_transform_string_stroke_trace_invalid_input_smoke)

    add_executable(test_sampling_unpremul_string_stroke_trace_invalid_input_smoke test/test_sampling_unpremul_string_stroke_trace_invalid_input_smoke.cpp)
    target_include_directories(test_sampling_unpremul_string_stroke_trace_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_sampling_unpremul_string_stroke_trace_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_sampling_unpremul_string_stroke_trace_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_sampling_unpremul_string_stroke_trace_invalid_input_smoke COMMAND test_sampling_unpremul_string_stroke_trace_invalid_input_smoke)

    add_executable(test_encoded_cubic_invalid_input_smoke test/test_encoded_cubic_invalid_input_smoke.cpp)
    target_include_directories(test_encoded_cubic_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_encoded_cubic_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_encoded_cubic_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_encoded_cubic_invalid_input_smoke COMMAND test_encoded_cubic_invalid_input_smoke)

    add_executable(test_annotation_android_codec_invalid_input_smoke test/test_annotation_android_codec_invalid_input_smoke.cpp)
    target_include_directories(test_annotation_android_codec_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_annotation_android_codec_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_annotation_android_codec_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_annotation_android_codec_invalid_input_smoke COMMAND test_annotation_android_codec_invalid_input_smoke)

    add_executable(test_contour_path_measure_invalid_input_smoke test/test_contour_path_measure_invalid_input_smoke.cpp)
    target_include_directories(test_contour_path_measure_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_contour_path_measure_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_contour_path_measure_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_contour_path_measure_invalid_input_smoke COMMAND test_contour_path_measure_invalid_input_smoke)

    add_executable(test_auto_canvas_restore_bbox_invalid_input_smoke test/test_auto_canvas_restore_bbox_invalid_input_smoke.cpp)
    target_include_directories(test_auto_canvas_restore_bbox_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_auto_canvas_restore_bbox_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_auto_canvas_restore_bbox_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_auto_canvas_restore_bbox_invalid_input_smoke COMMAND test_auto_canvas_restore_bbox_invalid_input_smoke)

    add_executable(test_data_table_invalid_input_smoke test/test_data_table_invalid_input_smoke.cpp)
    target_include_directories(test_data_table_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_data_table_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_data_table_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_data_table_invalid_input_smoke COMMAND test_data_table_invalid_input_smoke)

    add_executable(test_color_table_invalid_input_smoke test/test_color_table_invalid_input_smoke.cpp)
    target_include_directories(test_color_table_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_color_table_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_color_table_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_color_table_invalid_input_smoke COMMAND test_color_table_invalid_input_smoke)

    add_executable(test_mask_filter_invalid_input_smoke test/test_mask_filter_invalid_input_smoke.cpp)
    target_include_directories(test_mask_filter_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_mask_filter_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_mask_filter_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_mask_filter_invalid_input_smoke COMMAND test_mask_filter_invalid_input_smoke)

    add_executable(test_mask_invalid_input_smoke test/test_mask_invalid_input_smoke.cpp)
    target_include_directories(test_mask_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_mask_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_mask_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_mask_invalid_input_smoke COMMAND test_mask_invalid_input_smoke)

    add_executable(test_matrix_invalid_input_smoke test/test_matrix_invalid_input_smoke.cpp)
    target_include_directories(test_matrix_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_matrix_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_matrix_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_matrix_invalid_input_smoke COMMAND test_matrix_invalid_input_smoke)

    add_executable(test_m44_invalid_input_smoke test/test_m44_invalid_input_smoke.cpp)
    target_include_directories(test_m44_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_m44_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_m44_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_m44_invalid_input_smoke COMMAND test_m44_invalid_input_smoke)

    add_executable(test_vector_invalid_input_smoke test/test_vector_invalid_input_smoke.cpp)
    target_include_directories(test_vector_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_vector_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_vector_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_vector_invalid_input_smoke COMMAND test_vector_invalid_input_smoke)

    add_executable(test_vertices_invalid_input_smoke test/test_vertices_invalid_input_smoke.cpp)
    target_include_directories(test_vertices_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_vertices_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_vertices_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_vertices_invalid_input_smoke COMMAND test_vertices_invalid_input_smoke)

    add_executable(test_font_style_set_invalid_input_smoke test/test_font_style_set_invalid_input_smoke.cpp)
    target_include_directories(test_font_style_set_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_font_style_set_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_font_style_set_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_font_style_set_invalid_input_smoke COMMAND test_font_style_set_invalid_input_smoke)

    add_executable(test_font_invalid_input_smoke test/test_font_invalid_input_smoke.cpp)
    target_include_directories(test_font_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_font_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_font_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_font_invalid_input_smoke COMMAND test_font_invalid_input_smoke)

    add_executable(test_typeface_invalid_input_smoke test/test_typeface_invalid_input_smoke.cpp)
    target_include_directories(test_typeface_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_typeface_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_typeface_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_typeface_invalid_input_smoke COMMAND test_typeface_invalid_input_smoke)

    add_executable(test_font_arguments_metrics_invalid_input_smoke test/test_font_arguments_metrics_invalid_input_smoke.cpp)
    target_include_directories(test_font_arguments_metrics_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_font_arguments_metrics_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_font_arguments_metrics_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_font_arguments_metrics_invalid_input_smoke COMMAND test_font_arguments_metrics_invalid_input_smoke)

    add_executable(test_drawable_flattenable_invalid_input_smoke test/test_drawable_flattenable_invalid_input_smoke.cpp)
    target_include_directories(test_drawable_flattenable_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_drawable_flattenable_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_drawable_flattenable_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_drawable_flattenable_invalid_input_smoke COMMAND test_drawable_flattenable_invalid_input_smoke)

    add_executable(test_picture_recorder_invalid_input_smoke test/test_picture_recorder_invalid_input_smoke.cpp)
    target_include_directories(test_picture_recorder_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_picture_recorder_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_picture_recorder_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_picture_recorder_invalid_input_smoke COMMAND test_picture_recorder_invalid_input_smoke)

    add_executable(test_font_mgr_invalid_input_smoke test/test_font_mgr_invalid_input_smoke.cpp)
    target_include_directories(test_font_mgr_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_font_mgr_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_font_mgr_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_font_mgr_invalid_input_smoke COMMAND test_font_mgr_invalid_input_smoke)

    if(APPLE)
        add_executable(test_typeface_mac_invalid_input_smoke test/test_typeface_mac_invalid_input_smoke.cpp)
        target_include_directories(test_typeface_mac_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
        if(RESKIA_DEP_LINK_DIRS)
            target_link_directories(test_typeface_mac_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
        endif()
        target_link_libraries(test_typeface_mac_invalid_input_smoke reskia ${RESKIA_DEP_LIBS} "-framework CoreText")
        add_test(NAME c_skia_typeface_mac_invalid_input_smoke COMMAND test_typeface_mac_invalid_input_smoke)
    endif()

    add_executable(test_overdraw_canvas_invalid_input_smoke test/test_overdraw_canvas_invalid_input_smoke.cpp)
    target_include_directories(test_overdraw_canvas_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_overdraw_canvas_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_overdraw_canvas_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_overdraw_canvas_invalid_input_smoke COMMAND test_overdraw_canvas_invalid_input_smoke)

    add_executable(test_read_write_buffer_invalid_input_smoke test/test_read_write_buffer_invalid_input_smoke.cpp)
    target_include_directories(test_read_write_buffer_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_read_write_buffer_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_read_write_buffer_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_read_write_buffer_invalid_input_smoke COMMAND test_read_write_buffer_invalid_input_smoke)

    add_executable(test_region_invalid_input_smoke test/test_region_invalid_input_smoke.cpp)
    target_include_directories(test_region_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_region_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_region_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_region_invalid_input_smoke COMMAND test_region_invalid_input_smoke)

    add_executable(test_text_blob_invalid_input_smoke test/test_text_blob_invalid_input_smoke.cpp)
    target_include_directories(test_text_blob_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_text_blob_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_text_blob_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_text_blob_invalid_input_smoke COMMAND test_text_blob_invalid_input_smoke)

    add_executable(test_raster_handle_allocator_invalid_input_smoke test/test_raster_handle_allocator_invalid_input_smoke.cpp)
    target_include_directories(test_raster_handle_allocator_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_raster_handle_allocator_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_raster_handle_allocator_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_raster_handle_allocator_invalid_input_smoke COMMAND test_raster_handle_allocator_invalid_input_smoke)

    add_executable(test_ref_cnt_invalid_input_smoke test/test_ref_cnt_invalid_input_smoke.cpp)
    target_include_directories(test_ref_cnt_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_ref_cnt_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_ref_cnt_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_ref_cnt_invalid_input_smoke COMMAND test_ref_cnt_invalid_input_smoke)

    add_executable(test_pixel_ref_invalid_input_smoke test/test_pixel_ref_invalid_input_smoke.cpp)
    target_include_directories(test_pixel_ref_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_pixel_ref_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_pixel_ref_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_pixel_ref_invalid_input_smoke COMMAND test_pixel_ref_invalid_input_smoke)

    add_executable(test_pixmap_invalid_input_smoke test/test_pixmap_invalid_input_smoke.cpp)
    target_include_directories(test_pixmap_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_pixmap_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_pixmap_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_pixmap_invalid_input_smoke COMMAND test_pixmap_invalid_input_smoke)

    add_executable(test_codec_invalid_input_smoke test/test_codec_invalid_input_smoke.cpp)
    target_include_directories(test_codec_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_codec_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_codec_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_codec_invalid_input_smoke COMMAND test_codec_invalid_input_smoke)

    add_executable(test_decoder_invalid_input_smoke test/test_decoder_invalid_input_smoke.cpp)
    target_include_directories(test_decoder_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_decoder_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_decoder_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    if(RESKIA_ENABLE_AVIF)
        target_compile_definitions(test_decoder_invalid_input_smoke PRIVATE RESKIA_TEST_ENABLE_AVIF=1)
    endif()
    if(RESKIA_ENABLE_GIF)
        target_compile_definitions(test_decoder_invalid_input_smoke PRIVATE RESKIA_TEST_ENABLE_GIF=1)
    endif()
    if(RESKIA_ENABLE_JPEGXL)
        target_compile_definitions(test_decoder_invalid_input_smoke PRIVATE RESKIA_TEST_ENABLE_JPEGXL=1)
    endif()
    if(RESKIA_ENABLE_RAW)
        target_compile_definitions(test_decoder_invalid_input_smoke PRIVATE RESKIA_TEST_ENABLE_RAW=1)
    endif()
    add_test(NAME c_skia_decoder_invalid_input_smoke COMMAND test_decoder_invalid_input_smoke)

    add_executable(test_encoder_invalid_input_smoke test/test_encoder_invalid_input_smoke.cpp)
    target_include_directories(test_encoder_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_encoder_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_encoder_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    if(RESKIA_ENABLE_JPEG_ENCODER)
        target_compile_definitions(test_encoder_invalid_input_smoke PRIVATE RESKIA_TEST_ENABLE_JPEG_ENCODER=1)
    endif()
    if(RESKIA_ENABLE_WEBP_ENCODER)
        target_compile_definitions(test_encoder_invalid_input_smoke PRIVATE RESKIA_TEST_ENABLE_WEBP_ENCODER=1)
    endif()
    add_test(NAME c_skia_encoder_invalid_input_smoke COMMAND test_encoder_invalid_input_smoke)

    add_executable(test_image_generator_invalid_input_smoke test/test_image_generator_invalid_input_smoke.cpp)
    target_include_directories(test_image_generator_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_image_generator_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_image_generator_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_image_generator_invalid_input_smoke COMMAND test_image_generator_invalid_input_smoke)

    add_executable(test_images_invalid_input_smoke test/test_images_invalid_input_smoke.cpp)
    target_include_directories(test_images_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_images_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_images_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_images_invalid_input_smoke COMMAND test_images_invalid_input_smoke)

    add_executable(test_open_type_svg_decoder_invalid_input_smoke test/test_open_type_svg_decoder_invalid_input_smoke.cpp)
    target_compile_features(test_open_type_svg_decoder_invalid_input_smoke PRIVATE cxx_std_17)
    target_include_directories(test_open_type_svg_decoder_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_open_type_svg_decoder_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_open_type_svg_decoder_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_open_type_svg_decoder_invalid_input_smoke COMMAND test_open_type_svg_decoder_invalid_input_smoke)

    add_executable(test_image_filter_invalid_input_smoke test/test_image_filter_invalid_input_smoke.cpp)
    target_include_directories(test_image_filter_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_image_filter_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_image_filter_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_image_filter_invalid_input_smoke COMMAND test_image_filter_invalid_input_smoke)

    add_executable(test_tiled_image_utils_invalid_input_smoke test/test_tiled_image_utils_invalid_input_smoke.cpp)
    target_include_directories(test_tiled_image_utils_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_tiled_image_utils_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_tiled_image_utils_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_tiled_image_utils_invalid_input_smoke COMMAND test_tiled_image_utils_invalid_input_smoke)

    add_executable(test_runtime_effect_invalid_input_smoke test/test_runtime_effect_invalid_input_smoke.cpp)
    target_include_directories(test_runtime_effect_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    target_compile_features(test_runtime_effect_invalid_input_smoke PRIVATE cxx_std_17)
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_runtime_effect_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_runtime_effect_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_runtime_effect_invalid_input_smoke COMMAND test_runtime_effect_invalid_input_smoke)

    add_executable(test_mesh_specification_invalid_input_smoke test/test_mesh_specification_invalid_input_smoke.cpp)
    target_include_directories(test_mesh_specification_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_mesh_specification_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_mesh_specification_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_mesh_specification_invalid_input_smoke COMMAND test_mesh_specification_invalid_input_smoke)

    add_executable(test_mesh_invalid_input_smoke test/test_mesh_invalid_input_smoke.cpp)
    target_include_directories(test_mesh_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_mesh_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_mesh_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_mesh_invalid_input_smoke COMMAND test_mesh_invalid_input_smoke)

    add_executable(test_shader_invalid_input_smoke test/test_shader_invalid_input_smoke.cpp)
    target_include_directories(test_shader_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_shader_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_shader_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_shader_invalid_input_smoke COMMAND test_shader_invalid_input_smoke)

    add_executable(test_blenders_invalid_input_smoke test/test_blenders_invalid_input_smoke.cpp)
    target_include_directories(test_blenders_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_blenders_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_blenders_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_blenders_invalid_input_smoke COMMAND test_blenders_invalid_input_smoke)

    add_executable(test_blender_invalid_input_smoke test/test_blender_invalid_input_smoke.cpp)
    target_include_directories(test_blender_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_blender_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_blender_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_blender_invalid_input_smoke COMMAND test_blender_invalid_input_smoke)

    if(RESKIA_ENABLE_SKPARAGRAPH)
        add_executable(test_text_blob_run_handler_invalid_input_smoke test/test_text_blob_run_handler_invalid_input_smoke.cpp)
        target_include_directories(test_text_blob_run_handler_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
        if(RESKIA_DEP_LINK_DIRS)
            target_link_directories(test_text_blob_run_handler_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
        endif()
        target_link_libraries(test_text_blob_run_handler_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
        add_test(NAME c_skia_text_blob_run_handler_invalid_input_smoke COMMAND test_text_blob_run_handler_invalid_input_smoke)
    endif()

    add_executable(test_yuva_pixmaps_invalid_input_smoke test/test_yuva_pixmaps_invalid_input_smoke.cpp)
    target_include_directories(test_yuva_pixmaps_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_yuva_pixmaps_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_yuva_pixmaps_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_yuva_pixmaps_invalid_input_smoke COMMAND test_yuva_pixmaps_invalid_input_smoke)

    add_executable(test_yuva_info_invalid_input_smoke test/test_yuva_info_invalid_input_smoke.cpp)
    target_include_directories(test_yuva_info_invalid_input_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_yuva_info_invalid_input_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_yuva_info_invalid_input_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_yuva_info_invalid_input_smoke COMMAND test_yuva_info_invalid_input_smoke)

    if(APPLE AND TARGET svg AND TARGET skshaper AND TARGET skunicode)
        add_executable(test_shaping_smoke test/test_shaping_smoke.cpp)
        target_include_directories(test_shaping_smoke PRIVATE
                ${RESKIA_PUBLIC_INCLUDE_DIRS}
        )
        if(RESKIA_DEP_LINK_DIRS)
            target_link_directories(test_shaping_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
        endif()
        target_link_libraries(test_shaping_smoke reskia ${RESKIA_DEP_LIBS})
        add_test(NAME c_skia_shaping_smoke COMMAND test_shaping_smoke)

        add_executable(test_shaper_capi_smoke test/test_shaper_capi_smoke.cpp)
        target_include_directories(test_shaper_capi_smoke PRIVATE
                ${RESKIA_PUBLIC_INCLUDE_DIRS}
        )
        if(RESKIA_DEP_LINK_DIRS)
            target_link_directories(test_shaper_capi_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
        endif()
        target_link_libraries(test_shaper_capi_smoke reskia ${RESKIA_DEP_LIBS})
        add_test(NAME c_skia_shaper_capi_smoke COMMAND test_shaper_capi_smoke)
    endif()

    if(APPLE AND TARGET svg)
        add_executable(test_svg_dom_capi_smoke test/test_svg_dom_capi_smoke.cpp)
        target_include_directories(test_svg_dom_capi_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
        if(RESKIA_DEP_LINK_DIRS)
            target_link_directories(test_svg_dom_capi_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
        endif()
        target_link_libraries(test_svg_dom_capi_smoke reskia ${RESKIA_DEP_LIBS})
        add_test(NAME c_skia_svg_dom_capi_smoke COMMAND test_svg_dom_capi_smoke)
    endif()

    if(APPLE AND TARGET svg AND TARGET skresources)
        add_executable(test_svg_image_capi_smoke test/test_svg_image_capi_smoke.cpp)
        target_include_directories(test_svg_image_capi_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
        if(RESKIA_DEP_LINK_DIRS)
            target_link_directories(test_svg_image_capi_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
        endif()
        target_compile_definitions(test_svg_image_capi_smoke PRIVATE RESKIA_TEST_PNG_PATH="${RESKIA_ROOT_DIR}/third_party/src/libpng/pngtest.png")
        target_link_libraries(test_svg_image_capi_smoke reskia ${RESKIA_DEP_LIBS})
        add_test(NAME c_skia_svg_image_capi_smoke COMMAND test_svg_image_capi_smoke)
    endif()

    add_executable(test_svg_types_capi_smoke test/test_svg_types_capi_smoke.cpp)
    target_include_directories(test_svg_types_capi_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_svg_types_capi_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_svg_types_capi_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_svg_types_capi_smoke COMMAND test_svg_types_capi_smoke)

    add_executable(test_svg_canvas_capi_smoke test/test_svg_canvas_capi_smoke.cpp)
    target_include_directories(test_svg_canvas_capi_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
    if(RESKIA_DEP_LINK_DIRS)
        target_link_directories(test_svg_canvas_capi_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
    endif()
    target_link_libraries(test_svg_canvas_capi_smoke reskia ${RESKIA_DEP_LIBS})
    add_test(NAME c_skia_svg_canvas_capi_smoke COMMAND test_svg_canvas_capi_smoke)

    if(TARGET skunicode)
        add_executable(test_unicode_capi_smoke test/test_unicode_capi_smoke.cpp)
        target_include_directories(test_unicode_capi_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
        if(RESKIA_DEP_LINK_DIRS)
            target_link_directories(test_unicode_capi_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
        endif()
        target_link_libraries(test_unicode_capi_smoke reskia ${RESKIA_DEP_LIBS})
        add_test(NAME c_skia_unicode_capi_smoke COMMAND test_unicode_capi_smoke)
    endif()

    if(RESKIA_ENABLE_PDF)
        add_executable(test_pdf_smoke test/test_pdf_smoke.cpp)
        target_include_directories(test_pdf_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
        if(RESKIA_DEP_LINK_DIRS)
            target_link_directories(test_pdf_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
        endif()
        target_link_libraries(test_pdf_smoke reskia ${RESKIA_DEP_LIBS})
        add_test(NAME c_skia_pdf_smoke COMMAND test_pdf_smoke)
    endif()

    if(RESKIA_ENABLE_SKOTTIE)
        add_executable(test_skottie_smoke test/test_skottie_smoke.cpp)
        target_include_directories(test_skottie_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
        if(RESKIA_DEP_LINK_DIRS)
            target_link_directories(test_skottie_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
        endif()
        target_link_libraries(test_skottie_smoke reskia ${RESKIA_DEP_LIBS})
        add_test(NAME c_skia_skottie_smoke COMMAND test_skottie_smoke)
    endif()

    if(TARGET skresources)
        add_executable(test_skresources_capi_smoke test/test_skresources_capi_smoke.cpp)
        target_include_directories(test_skresources_capi_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
        if(RESKIA_DEP_LINK_DIRS)
            target_link_directories(test_skresources_capi_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
        endif()
        target_compile_definitions(test_skresources_capi_smoke PRIVATE RESKIA_TEST_PNG_PATH="${RESKIA_ROOT_DIR}/third_party/src/libpng/pngtest.png")
        target_link_libraries(test_skresources_capi_smoke reskia ${RESKIA_DEP_LIBS})
        add_test(NAME c_skia_skresources_capi_smoke COMMAND test_skresources_capi_smoke)
    endif()

    if(RESKIA_ENABLE_SKSG)
        add_executable(test_sksg_smoke test/test_sksg_smoke.cpp)
        target_include_directories(test_sksg_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
        if(RESKIA_DEP_LINK_DIRS)
            target_link_directories(test_sksg_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
        endif()
        target_link_libraries(test_sksg_smoke reskia ${RESKIA_DEP_LIBS})
        add_test(NAME c_skia_sksg_smoke COMMAND test_sksg_smoke)

        add_executable(test_sksg_capi_smoke test/test_sksg_capi_smoke.cpp)
        target_include_directories(test_sksg_capi_smoke PRIVATE ${RESKIA_PUBLIC_INCLUDE_DIRS})
        if(RESKIA_DEP_LINK_DIRS)
            target_link_directories(test_sksg_capi_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
        endif()
        target_link_libraries(test_sksg_capi_smoke reskia ${RESKIA_DEP_LIBS})
        add_test(NAME c_skia_sksg_capi_smoke COMMAND test_sksg_capi_smoke)
    endif()

    if(RESKIA_ENABLE_SKPARAGRAPH AND TARGET skshaper AND TARGET skunicode)
        add_executable(test_skparagraph_smoke test/test_skparagraph_smoke.cpp)
        target_include_directories(test_skparagraph_smoke PRIVATE
                ${RESKIA_PUBLIC_INCLUDE_DIRS}
        )
        if(RESKIA_DEP_LINK_DIRS)
            target_link_directories(test_skparagraph_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
        endif()
        target_link_libraries(test_skparagraph_smoke reskia ${RESKIA_DEP_LIBS})
        add_test(NAME c_skia_skparagraph_smoke COMMAND test_skparagraph_smoke)

        add_executable(test_paragraph_font_collection_capi_smoke test/test_paragraph_font_collection_capi_smoke.cpp)
        target_include_directories(test_paragraph_font_collection_capi_smoke PRIVATE
                ${RESKIA_PUBLIC_INCLUDE_DIRS}
        )
        if(RESKIA_DEP_LINK_DIRS)
            target_link_directories(test_paragraph_font_collection_capi_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
        endif()
        target_link_libraries(test_paragraph_font_collection_capi_smoke reskia ${RESKIA_DEP_LIBS})
        add_test(NAME c_skia_paragraph_font_collection_capi_smoke COMMAND test_paragraph_font_collection_capi_smoke)

        add_executable(test_paragraph_style_capi_smoke test/test_paragraph_style_capi_smoke.cpp)
        target_include_directories(test_paragraph_style_capi_smoke PRIVATE
                ${RESKIA_PUBLIC_INCLUDE_DIRS}
        )
        if(RESKIA_DEP_LINK_DIRS)
            target_link_directories(test_paragraph_style_capi_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
        endif()
        target_link_libraries(test_paragraph_style_capi_smoke reskia ${RESKIA_DEP_LIBS})
        add_test(NAME c_skia_paragraph_style_capi_smoke COMMAND test_paragraph_style_capi_smoke)

        add_executable(test_paragraph_text_style_capi_smoke test/test_paragraph_text_style_capi_smoke.cpp)
        target_include_directories(test_paragraph_text_style_capi_smoke PRIVATE
                ${RESKIA_PUBLIC_INCLUDE_DIRS}
        )
        if(RESKIA_DEP_LINK_DIRS)
            target_link_directories(test_paragraph_text_style_capi_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
        endif()
        target_link_libraries(test_paragraph_text_style_capi_smoke reskia ${RESKIA_DEP_LIBS})
        add_test(NAME c_skia_paragraph_text_style_capi_smoke COMMAND test_paragraph_text_style_capi_smoke)

        add_executable(test_paragraph_builder_capi_smoke test/test_paragraph_builder_capi_smoke.cpp)
        target_include_directories(test_paragraph_builder_capi_smoke PRIVATE
                ${RESKIA_PUBLIC_INCLUDE_DIRS}
        )
        if(RESKIA_DEP_LINK_DIRS)
            target_link_directories(test_paragraph_builder_capi_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
        endif()
        target_link_libraries(test_paragraph_builder_capi_smoke reskia ${RESKIA_DEP_LIBS})
        add_test(NAME c_skia_paragraph_builder_capi_smoke COMMAND test_paragraph_builder_capi_smoke)

        add_executable(test_paragraph_typeface_font_provider_capi_smoke test/test_paragraph_typeface_font_provider_capi_smoke.cpp)
        target_include_directories(test_paragraph_typeface_font_provider_capi_smoke PRIVATE
                ${RESKIA_PUBLIC_INCLUDE_DIRS}
        )
        if(RESKIA_DEP_LINK_DIRS)
            target_link_directories(test_paragraph_typeface_font_provider_capi_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
        endif()
        target_link_libraries(test_paragraph_typeface_font_provider_capi_smoke reskia ${RESKIA_DEP_LIBS})
        add_test(NAME c_skia_paragraph_typeface_font_provider_capi_smoke COMMAND test_paragraph_typeface_font_provider_capi_smoke)
    endif()

    if(APPLE AND RESKIA_ENABLE_GPU_GANESH AND RESKIA_ENABLE_GPU_METAL)
        add_executable(test_gpu_surface_capi_smoke test/test_gpu_surface_capi_smoke.mm)
        target_include_directories(test_gpu_surface_capi_smoke PRIVATE
                ${RESKIA_PUBLIC_INCLUDE_DIRS}
        )
        if(RESKIA_DEP_LINK_DIRS)
            target_link_directories(test_gpu_surface_capi_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
        endif()
        target_link_libraries(test_gpu_surface_capi_smoke reskia ${RESKIA_DEP_LIBS} "-framework Metal")
        add_test(NAME c_skia_gpu_surface_capi_smoke COMMAND test_gpu_surface_capi_smoke)
    endif()

    if(APPLE AND RESKIA_ENABLE_GPU_METAL AND (RESKIA_ENABLE_GPU_GANESH OR RESKIA_ENABLE_GPU_GRAPHITE))
        add_executable(test_gpu_context_capi_smoke test/test_gpu_context_capi_smoke.mm)
        target_include_directories(test_gpu_context_capi_smoke PRIVATE
                ${RESKIA_PUBLIC_INCLUDE_DIRS}
        )
        if(RESKIA_DEP_LINK_DIRS)
            target_link_directories(test_gpu_context_capi_smoke PRIVATE ${RESKIA_DEP_LINK_DIRS})
        endif()
        target_compile_definitions(test_gpu_context_capi_smoke PRIVATE
                RESKIA_TEST_GPU_GANESH=$<BOOL:${RESKIA_ENABLE_GPU_GANESH}>
                RESKIA_TEST_GPU_GRAPHITE=$<BOOL:${RESKIA_ENABLE_GPU_GRAPHITE}>
        )
        target_link_libraries(test_gpu_context_capi_smoke reskia ${RESKIA_DEP_LIBS} "-framework Metal")
        add_test(NAME c_skia_gpu_context_capi_smoke COMMAND test_gpu_context_capi_smoke)
    endif()
endif()
